### ISSUE TITLE
Installed hostdbviewer, how to see my contracts?

### ISSUE THREAD

**Issue by domini1000** [S-anasol/hostdbviewer#1]
Hi,
I installed the hostdbviewer like in the readme, but I changed the port in /config/index.js to 8888. Because 8080 is already in use.
I thougt i could see my own contracts now. But is see only these from your test server.
I think it is the obligations.js. But how to get this work with my host-data?
I thought the hostdbviewer get over api access to my contracts. Must i export data to see it?
If yes, how?
Domini1000

**Comment by sanasol** [comment]
Hi, this is very experimental feature :)

Sia wallet doesn't provide such api now.
So to export contracts need build custom Sia wallet version from this branch
https://github.com/S-anasol/Sia/commits/obligationsapi

Then export api result to JSON
`curl -A "Sia-Agent" "localhost:9980/host/storageobligations" > myobligations.json`

And then open this file with hostdbviewer, you can open it right here https://s-anasol.github.io/hostdbviewer/#/ via "Choose file" :)
